name: Test

on:
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.poetry/env

      - name: Install dependencies with Poetry
        run: poetry install

      - run: poetry run isort --recursive --diff .
      - run: poetry run black --check .
      - run: poetry run flake8
      - run: poetry run mypy
      - run: poetry run pytest --cov --cov-fail-under=100

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t best_practices:test

      - name: Smoke test docker image
        run: |
          docker run --rm best_practices:test 10
